config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :companies do
    resources :opportunities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :opportunities
end

app/models/opportunity.rb
class Opportunity < ApplicationRecord
  belongs_to :user
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :companies
  has_many :opportunities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :role])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :role])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    before_action :set_company, only: [:show, :edit, :update, :destroy]
    
    def index
        @companies = Company.all
    end

    def show
    end

    def new
        @company = Company.new
    end
    
    def edit
    end
    
      def create
        @company = Company.new(company_params)
        @company.user = current_user
        if @company.save
          flash[:success] = "Object successfully created"
          redirect_to @company
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
      end
    
      def update
        if @company.update(company_params)
          redirect_to @company, notice: 'company was successfully updated.'
        else
          render :edit
        end
      end
    
      def destroy
        @company.destroy
        redirect_to companys_url, notice: 'company was successfully destroyed.'
      end

    private

    def set_company
      @company = Company.find(params[:id])
    end
  
    def pet_params
      params.require(:company).permit(:name, :contact, :photo_url)
    end

end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
    before_action :set_opportunity, only: [:show, :edit, :update, :destroy]
    
    def index
        @opportunities = Opportunity.all
        @company = Company.find(params[:company_id])
    end

    def show
    end

    def new
      @company = Company.find(params[:company_id])
      @opportunity = Opportunity.new
    end
    
    def edit
    end
    
    def create
      @opportunity = Opportunity.new(opportunity_params)
      @company = Company.find(params[:company_id])
      @opportunity.user = current_user
      @opportunity.company = @company
      
        if @opportunity.save
          flash[:success] = "Object successfully created"
          redirect_to @opportunity
        else
          flash[:error] = "Something went wrong"
          render 'new'
      end
    end
    
    def update
        if @opportunity.update(opportunity_params)
          redirect_to @opportunity, notice: 'opportunity was successfully updated.'
        else
          render :edit
        end
    end
    
    def destroy
        @opportunity.destroy
        redirect_to opportunitys_url, notice: 'opportunity was successfully destroyed.'
    end

    private

    def set_opportunity
      @opportunity = Opportunity.find(params[:id])
    end
  
    def opportunity_params
      params.require(:opportunity).permit(:number, :date, :hour, :internal_code)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.erb
<div class="container">

    <div class="cards mt-4">
        <% @companies.each do |company|  %>
            <%= link_to company_path(company) do %>
                <div class="card-category-company" style='background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= company.photo_url %>)'>
                    <%= company.name %>
                </div>
            <% end%> 
        <% end %>
    </div>
</div>

app/views/companies/show.html.erb
<div class="container">
    <p>OPS</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GlobalShore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/opportunities/index.html.erb
<div class="container">

    <% @opportunities.each do |opportunity|  %>
        <%= link_to company_opportunities_path(opportunity) do %>
            <p><%= opportunity.number %></p>
        <% end %>    
    <% end %>

    <%= link_to 'Add Opportunity', new_company_opportunity_path(@company), class: "btn btn-blue mb-3"%>
</div>

app/views/opportunities/new.html.erb
<div class="container">
    <%= simple_form_for [@company, @opportunity] do |f| %> 
    <div class="form-inputs">
        <%= f.input :number %>
        <%= f.input :date %>
        <%= f.input :hour %>
        <%= f.input :internal_code %>
    </div>  
    <div class="form-actions">
        <%= f.button :submit , class: "btn btn-flat-log"%>
    </div>
    <% end %>
</div>

app/views/opportunities/show.html.erb
<div class="container">
    <p><%= @opportunity.number %></p>
    <p><%= @opportunity.date %></p>
    <p><%= @opportunity.hour %></p>
    <p><%= @opportunity.internal_code %></p>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Empresas", companies_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>